### ISSUE TITLE
本を書くための諸々

### ISSUE THREAD

**Issue by selmertsx** [selmertsx/todays_moderator#1]
## 順番

- まずはTypeScriptで普通に動くところまで持っていく
- テスト環境作る
- CI環境作る
- slackとのつなぎ込み
- APIの定義
  - serverlessを定期実行する方法の模索
- dynamoDBの設計

**Comment by selmertsx** [comment]
今回はslack botなので
まずは普通にslackからメッセージを受け取って、slackに通知できるところが先だろう。

**Comment by selmertsx** [comment]
tsの設定こんな感じにした。

```
export function lambda_handler(_event, _context, callback) {
  return callback("good message!");
}
```

- tsconfigの設定とtslintの設定はあとで見直す

**Comment by selmertsx** [comment]
https://github.com/vandium-io/lambda-tester#readme

**Comment by selmertsx** [comment]
https://github.com/mikechau/jest-lambda-tester-example/blob/master/test/lambda/index.spec.js

これを参考にしたら動いた。
https://github.com/vandium-io/lambda-tester/blob/master/examples/aws_service/test/index.test.js#L56-L71

packageの中にテストスクリプトあるんだな。これを使えばええやん。

**Comment by selmertsx** [comment]
lambdaの環境と合わせるために、nodejsのバージョンをv8.10.0に固定。
https://github.com/creationix/nvm#nvmrc

**Comment by selmertsx** [comment]
# CI環境作る

CircleCIを個人リポジトリでやる

<img width="1424" alt="2018-07-08 11 30 45" src="https://user-images.githubusercontent.com/1563239/42416181-8a27c7a4-82a2-11e8-94c2-3eb5377ec8c5.png">

<img width="1429" alt="2018-07-08 11 30 16" src="https://user-images.githubusercontent.com/1563239/42416183-8f6af678-82a2-11e8-9e07-dc30b5b8677b.png">

**Comment by selmertsx** [comment]
手順どおりやってく。
CircleCIのnode containerを探すけど、v8.10.0 が見つからない......!!
とりあえず指定して実行してみるよ。

**Comment by selmertsx** [comment]
```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn tsc
      - run: yarn test
```

この設定でとりあえず動いた。
